
using Autodesk.Revit.UI;
using Revit.Async.Entities;
using Revit.Async.Exceptions;
using Revit.Async.ExternalEvents;
using Revit.Async.Interfaces;
using System.Collections.Concurrent;


namespace Revit.Async
{
    /// <summary>
    ///     Provide some useful methods to support running Revit API code from any context
    /// </summary>
    public sealed class RevitTask : IRevitTask
    {
        private static readonly ConcurrentDictionary<Type, FutureExternalEvent> RegisteredExternalEvents = new();
        private readonly ConcurrentDictionary<Type, FutureExternalEvent> _scopedRegisteredExternalEvents = new();
        private bool _disposed;



        /// <inheritdoc />
        public void Dispose()
        {
            if (_disposed)
            {
                return;
            }

            _disposed = true;
            foreach (var externalEvent in _scopedRegisteredExternalEvents.Values)
            {
                externalEvent.Dispose();
            }

            _scopedRegisteredExternalEvents.Clear();
        }

        /// <inheritdoc />
        public Task<TResult> Raise<THandler, TParameter, TResult>(TParameter parameter)
            where THandler : IGenericExternalEventHandler<TParameter, TResult>
        {
            ThrowIfDisposed();
            if (_scopedRegisteredExternalEvents.TryGetValue(typeof(THandler), out var futureExternalEvent))
            {
                return futureExternalEvent.RunAsync<TParameter, TResult>(parameter);
            }

            throw new HandlerNotRegisteredException(typeof(THandler));
        }

        public Task<TResult> RaiseNew<THandler, TParameter, TResult>(TParameter parameter)
            where THandler : IGenericExternalEventHandler<TParameter, TResult>
        {
            ThrowIfDisposed();
            if (_scopedRegisteredExternalEvents.TryGetValue(typeof(THandler), out var futureExternalEvent))
            {
                return RunCloneAsync<TParameter, TResult>(futureExternalEvent, parameter);
            }

            throw new HandlerNotRegisteredException(typeof(THandler));
        }

        /// <inheritdoc />
        public void Register<TParameter, TResult>(IGenericExternalEventHandler<TParameter, TResult> handler)
        {
            ThrowIfDisposed();
            if (handler is null) throw new ArgumentNullException(nameof(handler));
            var futureExternalEvent = new FutureExternalEvent(handler);
            if (!_scopedRegisteredExternalEvents.TryAdd(handler.GetType(), futureExternalEvent))
            {
                futureExternalEvent.Dispose();
                throw new HandlerAlreadyRegisteredException(handler.GetType());
            }
        }



        /// <summary>
        ///     Always call this method ahead of time in Revit API context to make sure that <see cref="RevitTask" /> functions
        ///     properly
        /// </summary>
        public static void Initialize(UIControlledApplication application)
        {
            FutureExternalEvent.Initialize(application);
        }

        /// <summary>
        ///     Always call this method ahead of time in Revit API context to make sure that <see cref="RevitTask" /> functions
        ///     properly
        /// </summary>
        public static void Initialize(UIApplication application)
        {
            FutureExternalEvent.Initialize(application);
        }

        /// <summary>
        /// Releases global handlers and the service external event. Call from a valid Revit API context during shutdown.
        /// </summary>
        public static void Shutdown()
        {
            foreach (var externalEvent in RegisteredExternalEvents.Values)
            {
                externalEvent.Dispose();
            }

            RegisteredExternalEvents.Clear();
            FutureExternalEvent.Shutdown();
        }

        /// <summary>
        ///     Raise an <see cref="IGenericExternalEventHandler{TParameter,TResult}" /> and get the result.
        ///     If a the handler is not registered globally, find the RevitTask instance to raise it
        /// </summary>
        /// <typeparam name="THandler">The type of the <see cref="IGenericExternalEventHandler{TParameter,TResult}" /></typeparam>
        /// <typeparam name="TParameter">
        ///     The type of the parameter that
        ///     <see cref="IGenericExternalEventHandler{TParameter,TResult}" /> accepts
        /// </typeparam>
        /// <typeparam name="TResult">
        ///     The type of result that <see cref="IGenericExternalEventHandler{TParameter,TResult}" />
        ///     generates
        /// </typeparam>
        /// <param name="parameter">
        ///     The parameter passed to the <see cref="IGenericExternalEventHandler{TParameter,TResult}" />
        /// </param>
        /// <returns>The result generated by <see cref="IGenericExternalEventHandler{TParameter,TResult}" /></returns>
        public static Task<TResult> RaiseGlobal<THandler, TParameter, TResult>(TParameter parameter)
            where THandler : IGenericExternalEventHandler<TParameter, TResult>
        {
            if (RegisteredExternalEvents.TryGetValue(typeof(THandler), out var futureExternalEvent))
            {
                return futureExternalEvent.RunAsync<TParameter, TResult>(parameter);
            }

            throw new HandlerNotRegisteredException(typeof(THandler));
        }

        /// <summary>
        ///     Raise an <see cref="IGenericExternalEventHandler{TParameter,TResult}" /> and get the result.
        ///     If a the handler is not registered globally, find the RevitTask instance to raise it
        /// </summary>
        /// <typeparam name="THandler">The type of the <see cref="IGenericExternalEventHandler{TParameter,TResult}" /></typeparam>
        /// <typeparam name="TParameter">
        ///     The type of the parameter that
        ///     <see cref="IGenericExternalEventHandler{TParameter,TResult}" /> accepts
        /// </typeparam>
        /// <typeparam name="TResult">
        ///     The type of result that <see cref="IGenericExternalEventHandler{TParameter,TResult}" />
        ///     generates
        /// </typeparam>
        /// <param name="parameter">
        ///     The parameter passed to the <see cref="IGenericExternalEventHandler{TParameter,TResult}" />
        /// </param>
        /// <returns>The result generated by <see cref="IGenericExternalEventHandler{TParameter,TResult}" /></returns>
        public static Task<TResult> RaiseGlobalNew<THandler, TParameter, TResult>(TParameter parameter)
            where THandler : IGenericExternalEventHandler<TParameter, TResult>
        {
            if (RegisteredExternalEvents.TryGetValue(typeof(THandler), out var futureExternalEvent))
            {
                return RunCloneAsync<TParameter, TResult>(futureExternalEvent, parameter);
            }

            throw new HandlerNotRegisteredException(typeof(THandler));
        }

        /// <summary>
        ///     Register an <see cref="IGenericExternalEventHandler{TParameter,TResult}" /> to globally to be
        ///     raised. If a global handler is not what you want, make use of a RevitTask instance to register a scoped handler
        /// </summary>
        /// <typeparam name="TParameter">
        ///     The type of the parameter that
        ///     <see cref="IGenericExternalEventHandler{TParameter,TResult}" /> accepts
        /// </typeparam>
        /// <typeparam name="TResult">
        ///     The type of result that <see cref="IGenericExternalEventHandler{TParameter,TResult}" />
        ///     generates
        /// </typeparam>
        /// <param name="handler">The instance of <see cref="IGenericExternalEventHandler{TParameter,TResult}" /></param>
        public static void RegisterGlobal<TParameter, TResult>(IGenericExternalEventHandler<TParameter, TResult> handler)
        {
            if (handler is null) throw new ArgumentNullException(nameof(handler));
            var futureExternalEvent = new FutureExternalEvent(handler);
            if (!RegisteredExternalEvents.TryAdd(handler.GetType(), futureExternalEvent))
            {
                futureExternalEvent.Dispose();
                throw new HandlerAlreadyRegisteredException(handler.GetType());
            }
        }

        /// <summary>
        ///     Running Revit API code and get the result asynchronously
        /// </summary>
        /// <typeparam name="TResult">The type of the Result</typeparam>
        /// <param name="function">The delegate method wraps all the Revit API code with no argument</param>
        /// <returns></returns>
        public static Task<TResult> RunAsync<TResult>(Func<TResult> function)
        {
            return RunAsync(app => function());
        }

        /// <summary>
        ///     Running Revit API code and get the result asynchronously
        /// </summary>
        /// <typeparam name="TResult">The type of the Result</typeparam>
        /// <param name="function">The delegate method wraps all the Revit API code with <see cref="UIApplication" /> as argument</param>
        /// <returns>The result</returns>
        public static Task<TResult> RunAsync<TResult>(Func<UIApplication, TResult> function)
        {
            if (function is null) throw new ArgumentNullException(nameof(function));
            var handler             = new SyncDelegateExternalEventHandler<TResult>();
            var futureExternalEvent = new FutureExternalEvent(handler);
            return RunAndDisposeAsync<Func<UIApplication, TResult>, TResult>(futureExternalEvent, function);
        }

        /// <summary>
        ///     Running Revit API code and get the result asynchronously
        /// </summary>
        /// <typeparam name="TResult">The type of the Result</typeparam>
        /// <param name="function">
        ///     The delegate method wraps all the Revit API code and some other asynchronous processes with no
        ///     argument
        /// </param>
        /// <returns>The result</returns>
        public static Task<TResult> RunAsync<TResult>(Func<Task<TResult>> function)
        {
            return RunAsync(_ => function());
        }

        /// <summary>
        ///     Running Revit API code and get the result asynchronously
        /// </summary>
        /// <typeparam name="TResult">The type of the Result</typeparam>
        /// <param name="function">
        ///     The delegate method wraps all the Revit API code and some other asynchronous processes with
        ///     <see cref="UIApplication" /> as argument
        /// </param>
        /// <returns></returns>
        public static Task<TResult> RunAsync<TResult>(Func<UIApplication, Task<TResult>> function)
        {
            if (function is null) throw new ArgumentNullException(nameof(function));
            var handler             = new AsyncDelegateExternalEventHandler<TResult>();
            var futureExternalEvent = new FutureExternalEvent(handler);
            return RunAndDisposeAsync<Func<UIApplication, Task<TResult>>, TResult>(futureExternalEvent, function);
        }

        /// <summary>
        ///     Running Revit API code asynchronously
        /// </summary>
        /// <param name="action">The delegate method wraps all the Revit API code</param>
        /// <returns>The task indicating whether the execution has completed</returns>
        public static Task RunAsync(Action action)
        {
            return RunAsync(_ => action());
        }

        /// <summary>
        ///     Running Revit API code asynchronously
        /// </summary>
        /// <param name="action">The delegate method wraps all the Revit API code with <see cref="UIApplication" /> as argument</param>
        /// <returns>The task indicating whether the execution has completed</returns>
        public static Task RunAsync(Action<UIApplication> action)
        {
            return RunAsync(app =>
            {
                action(app);
                return true;
            });
        }

        /// <summary>
        ///     Running Revit API code asynchronously
        /// </summary>
        /// <param name="function">The delegate method wraps all the Revit API code and some other asynchronous processes</param>
        /// <returns>The task indicating whether the execution has completed</returns>
        public static Task RunAsync(Func<Task> function)
        {
            return RunAsync(_ => function());
        }

        /// <summary>
        ///     Running Revit API code asynchronously
        /// </summary>
        /// <param name="function">
        ///     The delegate method wraps all the Revit API code and some other asynchronous processes with
        ///     <see cref="UIApplication" /> as argument
        /// </param>
        /// <returns></returns>
        public static Task RunAsync(Func<UIApplication, Task> function)
        {
            if (function is null) throw new ArgumentNullException(nameof(function));
            return RunAsync(async app =>
            {
                await function(app).ConfigureAwait(false);
                return true;
            });
        }

        private static async Task<TResult> RunAndDisposeAsync<TParameter, TResult>(
            FutureExternalEvent futureExternalEvent,
            TParameter parameter)
        {
            using (futureExternalEvent)
            {
                return await futureExternalEvent.RunAsync<TParameter, TResult>(parameter).ConfigureAwait(false);
            }
        }

        private static async Task<TResult> RunCloneAsync<TParameter, TResult>(
            FutureExternalEvent source,
            TParameter parameter)
        {
            var clone = (FutureExternalEvent)source.Clone();
            return await RunAndDisposeAsync<TParameter, TResult>(clone, parameter).ConfigureAwait(false);
        }

        private void ThrowIfDisposed()
        {
            if (_disposed)
            {
                throw new ObjectDisposedException(nameof(RevitTask));
            }
        }

    }
}
